### ISSUE TITLE
Concerning ChadwickLibrary.libchadwick

### ISSUE THREAD

**Issue by Vinnie-Palazeti** [bdilday/pychadwick#25]
![image](https://user-images.githubusercontent.com/53910909/106645570-8a7f6980-655a-11eb-9793-8de03503c592.png)

Running into this error on both Windows & Mac machines. An error is being raised from the ChadwickLibrary class in the libutils

**Comment by bdilday** [comment]
I think I fixed this. Would you mind trying installing this [test version](https://test.pypi.org/project/pychadwick/0.5.0.dev0/) and seeing if it fixes the issue?
i.e, 
`$ pip install -i https://test.pypi.org/simple/ pychadwick==0.5.0.dev0`

**Comment by bdilday** [comment]
sorry that should be 
`$ pip install --extra-index-url https://test.pypi.org/simple/ pychadwick==0.5.0.dev0`

**Comment by Vinnie-Palazeti** [comment]
Works like a charm. Thank you!

I have one more question if you don't mind. Do you know when retrosheet &
chadwick update new regular season games? Is it directly after each game,
or at the end of the season?

Thanks I appreciate the help with installation

Vinnie

**Comment by bdilday** [comment]
Thanks for checking! They don't update after the games, it's a few months after the season ends.
